-- LifeOS initial Supabase/Postgres schema
-- Run this in Supabase SQL Editor before pointing the API at Postgres.

begin;

create extension if not exists pgcrypto;

create table if not exists users (
  id integer generated by default as identity primary key,
  google_id text unique,
  email text not null unique,
  password_hash text,
  name text not null,
  avatar_url text,
  timezone text not null default 'Asia/Manila',
  tone text not null default 'gentle' check (tone in ('gentle', 'neutral', 'direct')),
  quiet_hours_start time,
  quiet_hours_end time,
  reminders_enabled boolean not null default true,
  habit_nudges_enabled boolean not null default true,
  weekly_recap_enabled boolean not null default true,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp
);

create table if not exists projects (
  id integer generated by default as identity primary key,
  user_id integer not null references users(id) on delete cascade,
  name text not null,
  description text,
  color text,
  sort_order integer not null default 0,
  archived_at timestamptz,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp
);

create index if not exists projects_user_id_idx on projects (user_id);
create index if not exists projects_user_sort_idx on projects (user_id, sort_order, created_at desc);

create table if not exists tasks (
  id integer generated by default as identity primary key,
  user_id integer not null references users(id) on delete cascade,
  project_id integer references projects(id) on delete set null,
  title text not null,
  notes text,
  status text not null default 'todo' check (status in ('backlog', 'todo', 'doing', 'done')),
  priority text not null default 'medium' check (priority in ('low', 'medium', 'high')),
  due_date date,
  completed_at timestamptz,
  sort_order integer not null default 0,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp
);

create index if not exists tasks_user_id_idx on tasks (user_id);
create index if not exists tasks_user_status_idx on tasks (user_id, status);
create index if not exists tasks_user_project_idx on tasks (user_id, project_id);
create index if not exists tasks_user_due_idx on tasks (user_id, due_date);

create table if not exists habits (
  id integer generated by default as identity primary key,
  user_id integer not null references users(id) on delete cascade,
  name text not null,
  description text,
  active boolean not null default true,
  sort_order integer not null default 0,
  cadence text not null default 'daily' check (cadence in ('daily', 'weekly')),
  target_per_period integer not null default 1 check (target_per_period > 0),
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp
);

create index if not exists habits_user_id_idx on habits (user_id);
create index if not exists habits_user_active_idx on habits (user_id, active);
create index if not exists habits_user_sort_idx on habits (user_id, sort_order, created_at desc);

create table if not exists habit_checkins (
  id integer generated by default as identity primary key,
  user_id integer not null references users(id) on delete cascade,
  habit_id integer not null references habits(id) on delete cascade,
  checkin_date date not null,
  value integer not null default 1 check (value > 0),
  created_at timestamptz not null default current_timestamp,
  unique (user_id, habit_id, checkin_date)
);

create index if not exists habit_checkins_user_habit_idx on habit_checkins (user_id, habit_id);
create index if not exists habit_checkins_user_date_idx on habit_checkins (user_id, checkin_date);

create table if not exists reflections (
  id integer generated by default as identity primary key,
  user_id integer not null references users(id) on delete cascade,
  reflect_date date not null,
  mood integer check (mood between 1 and 5),
  gratitude text,
  highlights text,
  challenges text,
  notes text,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp,
  unique (user_id, reflect_date)
);

create index if not exists reflections_user_date_idx on reflections (user_id, reflect_date desc);

create table if not exists reminders (
  id integer generated by default as identity primary key,
  user_id integer not null references users(id) on delete cascade,
  entity_type text not null check (entity_type in ('habit', 'task')),
  entity_id integer not null,
  enabled boolean not null default true,
  schedule_type text not null default 'daily' check (schedule_type in ('daily', 'weekly', 'cron')),
  due_at timestamptz,
  time_of_day time,
  days_of_week text[],
  cron_expr text,
  respect_quiet_hours boolean not null default true,
  last_run_at timestamptz,
  next_run_at timestamptz,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp
);

create index if not exists reminders_user_id_idx on reminders (user_id);
create index if not exists reminders_user_enabled_next_run_idx on reminders (user_id, enabled, next_run_at);
create index if not exists reminders_enabled_next_run_idx on reminders (enabled, next_run_at);

create table if not exists push_subscriptions (
  id integer generated by default as identity primary key,
  user_id integer not null references users(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  user_agent text,
  last_seen_at timestamptz not null default current_timestamp,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp
);

create index if not exists push_subscriptions_user_id_idx on push_subscriptions (user_id);

create table if not exists notification_log (
  id integer generated by default as identity primary key,
  user_id integer not null references users(id) on delete cascade,
  reminder_id integer not null references reminders(id) on delete cascade,
  run_key text not null unique,
  sent_at timestamptz not null default current_timestamp,
  status text not null check (status in ('sent', 'skipped', 'failed')),
  error_message text
);

create index if not exists notification_log_user_sent_idx on notification_log (user_id, sent_at desc);
create index if not exists notification_log_reminder_idx on notification_log (reminder_id, sent_at desc);

commit;
